import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join } from 'node:path';
import { URL } from 'node:url';
const PORT=process.env.PORT||3000, ROOT=new URL('.',import.meta.url).pathname;
let ebayCache={token:null,expires:0};
async function ebayToken(){const id=process.env.EBAY_CLIENT_ID,secret=process.env.EBAY_CLIENT_SECRET;if(!id||!secret)return null;if(ebayCache.token&&Date.now()<ebayCache.expires)return ebayCache.token;const auth=Buffer.from(`${id}:${secret}`).toString('base64'),body=new URLSearchParams({grant_type:'client_credentials',scope:'https://api.ebay.com/oauth/api_scope'}),r=await fetch('https://api.ebay.com/identity/v1/oauth2/token',{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error(`eBay token failed (${r.status})`);const d=await r.json();ebayCache={token:d.access_token,expires:Date.now()+Math.max(60,(d.expires_in||7200)-120)*1000};return ebayCache.token}
async function ebaySearch({upc=null,query=null}){const token=await ebayToken();if(!token)return null;const url=new URL('https://api.ebay.com/buy/browse/v1/item_summary/search');if(upc)url.searchParams.set('gtin',upc);else if(query)url.searchParams.set('q',query);else return null;url.searchParams.set('limit','40');url.searchParams.set('filter','buyingOptions:{FIXED_PRICE}');const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`,'X-EBAY-C-MARKETPLACE-ID':'EBAY_US'}});if(!r.ok)throw new Error(`eBay lookup failed (${r.status})`);const d=await r.json(),items=(d.itemSummaries||[]).filter(x=>x.price?.value).map(x=>({title:x.title,price:Number(x.price.value)})).filter(x=>Number.isFinite(x.price)&&x.price>0);if(!items.length)return null;const prices=items.map(x=>x.price).sort((a,b)=>a-b);const trim=prices.length>=8?prices.slice(Math.floor(prices.length*.1),Math.ceil(prices.length*.9)):prices,median=trim[Math.floor(trim.length/2)];return{name:items[0].title,price:median,count:items.length,method:upc?'UPC':'keyword'}}
async function keepaLookup(upc){const key=process.env.KEEPA_API_KEY;if(!key)return null;const url=new URL('https://api.keepa.com/product');url.searchParams.set('key',key);url.searchParams.set('domain','1');url.searchParams.set('code',upc);url.searchParams.set('stats','90');const r=await fetch(url,{headers:{'Accept-Encoding':'gzip'}});if(!r.ok)throw new Error(`Keepa lookup failed (${r.status})`);const d=await r.json(),p=d.products?.[0];if(!p)return null;let price=null;const current=p.stats?.current;if(Array.isArray(current)){for(const idx of [18,0,1,2,3]){const v=current[idx];if(Number.isFinite(v)&&v>0){price=v/100;break}}}return{name:p.title||null,price,asin:p.asin||null,tokensLeft:d.tokensLeft}}
function json(res,status,obj){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(obj))}
async function handleLookup(res,upc){if(!/^\d{8,14}$/.test(upc))return json(res,400,{message:'Enter a valid 8–14 digit UPC/GTIN.'});const out={upc,amazonPrice:null,ebayPrice:null,name:null,message:'',sources:{}};const msgs=[];let keepa=null,ebay=null;try{keepa=await keepaLookup(upc);if(keepa){out.name=keepa.name||out.name;out.amazonPrice=keepa.price;out.sources.keepa={asin:keepa.asin,tokensLeft:keepa.tokensLeft};msgs.push(keepa.price?'Amazon/Keepa match found.':'Keepa matched the product, but no usable current price was returned.')}else if(process.env.KEEPA_API_KEY)msgs.push('No Keepa match.')}catch(e){msgs.push(`Keepa error: ${e.message}`)}try{ebay=await ebaySearch({upc});if(!ebay&&out.name)ebay=await ebaySearch({query:out.name});if(ebay){out.name=out.name||ebay.name;out.ebayPrice=ebay.price;out.sources.ebay={listings:ebay.count,method:ebay.method};msgs.push(`eBay found ${ebay.count} current fixed-price listings by ${ebay.method==='UPC'?'UPC':'product-name fallback'}; using the median asking price.`)}else if(process.env.EBAY_CLIENT_ID&&process.env.EBAY_CLIENT_SECRET)msgs.push('No eBay match by UPC or product name.')}catch(e){msgs.push(`eBay error: ${e.message}`)}out.message=msgs.join(' ')||'No live APIs are connected yet. Enter resale prices manually.';return json(res,200,out)}
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.webmanifest':'application/manifest+json','.svg':'image/svg+xml'};
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host}`);if(u.pathname==='/api/config')return json(res,200,{ebay:!!(process.env.EBAY_CLIENT_ID&&process.env.EBAY_CLIENT_SECRET),keepa:!!process.env.KEEPA_API_KEY});if(u.pathname==='/api/lookup')return handleLookup(res,(u.searchParams.get('upc')||'').trim());let path=u.pathname==='/'?'index.html':u.pathname.slice(1);if(path.includes('..')){res.writeHead(400);return res.end('Bad request')}try{const data=await readFile(join(ROOT,path));res.writeHead(200,{'Content-Type':types[extname(path)]||'application/octet-stream'});res.end(data)}catch{res.writeHead(404);res.end('Not found')}});server.listen(PORT,()=>console.log(`Flip Finder running at http://localhost:${PORT}`));
