import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join } from 'node:path';
import { URL } from 'node:url';
const PORT=process.env.PORT||3000, ROOT=new URL('.',import.meta.url).pathname;
let ebayCache={token:null,expires:0};
async function ebayToken(){const id=process.env.EBAY_CLIENT_ID,secret=process.env.EBAY_CLIENT_SECRET;if(!id||!secret)return null;if(ebayCache.token&&Date.now()<ebayCache.expires)return ebayCache.token;const auth=Buffer.from(`${id}:${secret}`).toString('base64'),body=new URLSearchParams({grant_type:'client_credentials',scope:'https://api.ebay.com/oauth/api_scope'}),r=await fetch('https://api.ebay.com/identity/v1/oauth2/token',{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error(`eBay token failed (${r.status})`);const d=await r.json();ebayCache={token:d.access_token,expires:Date.now()+Math.max(60,(d.expires_in||7200)-120)*1000};return ebayCache.token}
async function ebayLookup(upc){const token=await ebayToken();if(!token)return null;const url=new URL('https://api.ebay.com/buy/browse/v1/item_summary/search');url.searchParams.set('gtin',upc);url.searchParams.set('limit','30');url.searchParams.set('filter','buyingOptions:{FIXED_PRICE}');const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`,'X-EBAY-C-MARKETPLACE-ID':'EBAY_US'}});if(!r.ok)throw new Error(`eBay lookup failed (${r.status})`);const d=await r.json(),items=(d.itemSummaries||[]).filter(x=>x.price?.value).map(x=>({title:x.title,price:Number(x.price.value)})).filter(x=>Number.isFinite(x.price)&&x.price>0);if(!items.length)return null;const prices=items.map(x=>x.price).sort((a,b)=>a-b),median=prices[Math.floor(prices.length/2)];return{name:items[0].title,price:median,count:items.length}}
async function keepaLookup(upc){const key=process.env.KEEPA_API_KEY;if(!key)return null;const url=new URL('https://api.keepa.com/product');url.searchParams.set('key',key);url.searchParams.set('domain','1');url.searchParams.set('code',upc);url.searchParams.set('stats','90');const r=await fetch(url,{headers:{'Accept-Encoding':'gzip'}});if(!r.ok)throw new Error(`Keepa lookup failed (${r.status})`);const d=await r.json(),p=d.products?.[0];if(!p)return null;let price=null;const current=p.stats?.current;if(Array.isArray(current)){for(const idx of [18,0,1,2,3]){const v=current[idx];if(Number.isFinite(v)&&v>0){price=v/100;break}}}return{name:p.title||null,price,asin:p.asin||null,tokensLeft:d.tokensLeft}}
function json(res,status,obj){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(obj))}
async function handleLookup(res,upc){if(!/^\d{8,14}$/.test(upc))return json(res,400,{message:'Enter a valid 8–14 digit UPC/GTIN.'});const out={upc,amazonPrice:null,ebayPrice:null,name:null,message:'',sources:{}};const tasks=[keepaLookup(upc).then(x=>({k:'keepa',x})).catch(e=>({k:'keepa',e})),ebayLookup(upc).then(x=>({k:'ebay',x})).catch(e=>({k:'ebay',e}))];const rs=await Promise.all(tasks),msgs=[];for(const r of rs){if(r.k==='keepa'){if(r.x){out.name=out.name||r.x.name;out.amazonPrice=r.x.price;out.sources.keepa={asin:r.x.asin,tokensLeft:r.x.tokensLeft};msgs.push(r.x.price?'Amazon/Keepa match found.':'Keepa matched the product, but no usable current price was returned.')}else if(process.env.KEEPA_API_KEY)msgs.push(r.e?`Keepa error: ${r.e.message}`:'No Keepa match.')}else{if(r.x){out.name=out.name||r.x.name;out.ebayPrice=r.x.price;out.sources.ebay={listings:r.x.count};msgs.push(`eBay found ${r.x.count} current fixed-price listings; using the median asking price.`)}else if(process.env.EBAY_CLIENT_ID&&process.env.EBAY_CLIENT_SECRET)msgs.push(r.e?`eBay error: ${r.e.message}`:'No eBay match.')}}out.message=msgs.join(' ')||'No live APIs are connected yet. Enter resale prices manually.';return json(res,200,out)}
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.webmanifest':'application/manifest+json','.svg':'image/svg+xml'};
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host}`);if(u.pathname==='/api/config')return json(res,200,{ebay:!!(process.env.EBAY_CLIENT_ID&&process.env.EBAY_CLIENT_SECRET),keepa:!!process.env.KEEPA_API_KEY});if(u.pathname==='/api/lookup')return handleLookup(res,(u.searchParams.get('upc')||'').trim());let path=u.pathname==='/'?'index.html':u.pathname.slice(1);if(path.includes('..')){res.writeHead(400);return res.end('Bad request')}try{const data=await readFile(join(ROOT,path));res.writeHead(200,{'Content-Type':types[extname(path)]||'application/octet-stream'});res.end(data)}catch{res.writeHead(404);res.end('Not found')}});server.listen(PORT,()=>console.log(`Flip Finder running at http://localhost:${PORT}`));
